### ISSUE TITLE
evn variable ANDROID_CLIENT_IDS absent halts server boot.

### ISSUE THREAD

**Issue by BrockMcKean** [gdg-x/hub#120]
`npm run startDev` and `npm start` both yield the same problem for me with empty ANDROID_CLIENT_IDS...

```
Waiting.../Users/brock/repos/gdg-x/hub/lib/config/keys.js:15
      androidClientIds: process.env.ANDROID_CLIENT_IDS.split(',')
                                                      ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/Users/brock/repos/gdg-x/hub/lib/config/keys.js:15:55)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brock/repos/gdg-x/hub/lib/config/config.js:10:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Not sure what the problem is, but I'm digging right now.

**Comment by Splaktar** [comment]
Pushed up a fix to my branch: https://github.com/gdg-x/hub/commit/b2b22e5727f881577f50681c7114cf56714430a9

**Comment by BrockMcKean** [comment]
Haha, I guess I could have done that... I didn’t know if I was breaking anything. 
Thanks!

**Comment by Splaktar** [comment]
No problem, it should only need to be defined in production.
