### ISSUE TITLE
If Redis can't be contacted, the Hub stops serving content and goes down

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#77]
Redis disconnect issues appear to have taken down the hub at 6:56pm ET today:

```
[30384] Express server listening on port 3000 in production mode
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 130.211.142.195:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/opt/hub/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/opt/hub/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
[17884] worker 30384 died. Code: 1, Signal: null
[17884] worker 30389 born.
```

**Comment by Splaktar** [comment]
This is affecting both nodes.

Restarting Hub nodes and Redis nodes did not resolve this. Networking hasn't been changed and settings still appear to be valid.

**Comment by Splaktar** [comment]
Back online. I had to redeploy a new Redis cluster in the gdg-x network and then point the Hub nodes to this new cluster. 

The previous cluster was in the default network, but there were network firewall rules that should have made it reachable. There was a warning in the redis coordinator VM that the Debian 7 image it was using was deprecated, but that should not have caused this.

**Comment by Splaktar** [comment]
We should probably update the code so that if the connection to Redis fails, it does not bring down the server.

**Comment by Splaktar** [comment]
Now Redis is failing for another reason:

```
/opt/hub/node_modules/redis/index.js:575
                throw callback_err;
                      ^
Error: Ready check failed: NOAUTH Authentication required.
    at RedisClient.on_info_cmd (/opt/hub/node_modules/redis/index.js:380:35)
    at Command.callback (/opt/hub/node_modules/redis/index.js:430:14)
    at RedisClient.return_error (/opt/hub/node_modules/redis/index.js:571:25)
    at ReplyParser.<anonymous> (/opt/hub/node_modules/redis/index.js:317:18)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_error (/opt/hub/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/hub/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/hub/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/opt/hub/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
```

**Comment by Splaktar** [comment]
There were issues communicating with redis-vm-3 this week. It turns out that the `redis-server` service on that node had stopped and didn't restart on reboot. I've reinstalled the `redis-server` via `apt-get` and it seems to be working again.

Hub is now pointing at redis-vm-3 and Hub-backup at redis-vm-1.

**Comment by Splaktar** [comment]
This is no longer relevant as we plan to remove Redis as part of #104.
