### ISSUE TITLE
Redis suddenly failing Auth

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#79]
Now Redis is failing for another reason. It was working just fine for a couple of days, nothing changed... and then this happened...

```
/opt/hub/node_modules/redis/index.js:575
                throw callback_err;
                      ^
Error: Ready check failed: NOAUTH Authentication required.
    at RedisClient.on_info_cmd (/opt/hub/node_modules/redis/index.js:380:35)
    at Command.callback (/opt/hub/node_modules/redis/index.js:430:14)
    at RedisClient.return_error (/opt/hub/node_modules/redis/index.js:571:25)
    at ReplyParser.<anonymous> (/opt/hub/node_modules/redis/index.js:317:18)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_error (/opt/hub/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/hub/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/hub/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/opt/hub/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
```

**Comment by Splaktar** [comment]
This is finally fixed. See #78 for details.
